.github/workflows/ci.yml
bin/test
la/vector.v

With this PR, syntax errors and other problems will fail the whole
`make test` CI job run, so that they can be discovered quicker.

ci: fix syntax error in la/vector.v, let `make test` fail, when any test fail

---

comb/comb.v
comb/comb_test.v
fun/fun.v

First version of an entirely eager version of combinations with replacement

comb: working version of combinations_with_replacements

---

la/matrix.v
la/matrix_test.v

1. Added unit tests for all public functions in `vsl.la.matrix.v`
2. Fixed minor typos

Add unit tests for matrix

---

vsl/errors/errno.v
vsl/fun/interpcubic.v
vsl/fun/interpcubic_test.v
vsl/fun/interpquad.v
vsl/fun/interpquad_test.v
vsl/fun/sinusoid.v
vsl/fun/sinusoid_test.v
vsl/fun/util.v
vsl/gm/bins.v

This PR adds interpolation functions for #41
- `InterpQuad` computes a quadratic polynomial to perform interpolation either using 3 points or 2 points and a known derivative
- `InterpCubic` computes a cubic polynomial to perform interpolation either using 4 points or 3 points and a known derivative
- Also added structure that implements the sinusoid equation

Feature Interpolation: Adds interpolation functions to vsl.fun

---

ml/knn.v

I also changed .efailed to .einval in `knn.v`. If any other typos are found, let me know.

Fix typo and made sure ties will not end up in an infinite loop.

---

plot/README.md
plot/annotation.v
plot/axis.v
plot/create-venv.sh
plot/examples/bar.v
plot/examples/pie.v
plot/examples/scatter.v
plot/font.v
plot/layout.v
plot/plot.v
plot/plotter.py
plot/run.sh
plot/trace.v

Added initial code for the first release of the plotting tool - which is simply a JSON dumper that gives the graph information to a Python script that renders it with Plotly.

Initial release of vsl.plot

---

.github/workflows/docs-ci.yml
vcl/kernel.c.v

<!--
```
fn foo() {
// file_test.v
...
}
```
->

update error type

---

blas/conversions.v
blas/lapack.v
graph/graph.v
la/densesol.v
la/matrix_ops.v

After PR https://github.com/vlang/v/pull/13827
V will no longer allow capital letters to start parameter names.
This PR fixes compilation in light of that change.
It also fixes warnings, that prevent -prod compilation.

fix compilation with latest v (after PR 13827)

---

.github/workflows/ci.yml
blas/README.md
la/blas.v
la/matrix.v
la/matrix_ops.v
ml/data.v
ml/kmeans.v
ml/knn.v
ml/linreg.v
ml/linreg_test.v
ml/paramsreg.v
ml/paramsreg_test.v
ml/workspace.v
ml/workspace_test.v

<!--
```
fn foo() {
// file_test.v
...
}
```
->

vsl.la: Reimplement vsl.la and vsl.ml using generics

---

prime/prime.v
prime/prime_test.v

Add `is_prime` function and `prime_sieve` which can generate all primes up to n

prime: new module

---

.github/workflows/ci.yml
la/densesol.v
noise/perlin.v
noise/perlin_test.v
noise/readme.md

saw there was an open issue, here you go

noise: implement 2d perlin noise (#42)

---

.devcontainer/devcontainer.json
.gitignore

- automatically install vlang vscode plugin in devcontainer
- automatically install c++ plugin for debugging in devcontainer
- git ignore vsl logfile

devcontainer: add vlang plugin & cpp plugin

---

easings/easings.v

This PR fix generic fn call in easings.v.

fix generic fn call in easings.v

---

ml/linreg.v
ml/workspace.v

This PR fix generic fn call argument mismatch.

fix generic fn call argument mismatch

---

float/float32/axpy_test.v
float/float64/axpy_test.v
float/float64/gemv_test.v
gm/bins.v
graph/graph.v
graph/graph_test.v

This PR fix error for array assign.

fix error for array assign

---

.github/workflows/ci.yml
examples/opencl_vcl_basic/main_not_ci.v
la/blas.v
la/densesol.v
la/matrix.v
la/matrix_ops.v
la/matrix_ops_test.v
la/matrix_test.v
la/sparse_matrix.v
la/vector.v
ml/data.v
ml/data_test.v
ml/kmeans.v
ml/knn.v
ml/linreg.v
ml/paramsreg.v
ml/paramsreg_test.v
ml/workspace.v
ml/workspace_test.v
util/util.v
vcl/kernel.c.v
vcl/vector.c.v
vlas/README.md

<!--
```
fn foo() {
// file_test.v
...
}
```
->

Make V fmt check pass again

---

examples/ml_sentiment_analysis/main.v
la/sparse_config.v

<!--
```
fn foo() {
// file_test.v
...
}
```
->

Added communicator

---

noise/README.md
noise/perlin_test.v

Fixes for #127.
<!--
```
fn foo() {
// file_test.v
...
}
```
->

adopt useful seeds; test for close but not exact results

---

vcl/README.md
vcl/_cflags_d_dlopencl.v
vcl/_cfun_d_dlopencl.c.v

this is only 1 step for complete termux suport
<!--
```
fn foo() {
// file_test.v
...
}
```
->

1 step termux dlopencl

---

vcl/README.md
vcl/_cfun_d_dlopencl.c.v
vcl/utils/_cfun_d_globalcl.c.v
vcl/utils/path_darwin.c.v
vcl/utils/paths_android.c.v
vcl/utils/paths_default.c.v
vcl/utils/paths_linux.c.v
vcl/utils/paths_termux.c.v
vcl/utils/paths_windows.c.v
vcl/vcl.c.v

@ulises-jeremias well I know that is little bit ennoying, but I like have options ..., and I little bit sort constant  paths and I make it the .clone() is not nesessery ...

add (3.) option non global dlopen

---

examples/vcl_opencl_image_example/kernel.cl
examples/vcl_opencl_image_example/main.v
vcl/image.c.v

small sugest to another improve

Img from bytes

---

prime/prime.v

<!--
```
fn foo() {
// file_test.v
...
}
```
->

optimalization prime

---

fun/interpcubic.v
fun/interpcubic_test.v
fun/interpquad.v
fun/interpquad_test.v

This PR fix option to result in fun.

fix option to result in fun

---

fft/README.md
fft/_cflags.c.v
fft/fft.v
fft/fft64_test.v
fft/fft_test.v
fft/src/LICENSE.md
fft/src/README.md
fft/src/f32.c
fft/src/f64.c
fft/src/pocketfft_f32.h
fft/src/pocketfft_f64.h
fft/v.mod

This is a wrapper on the PocketFFT code in C, which was in turn modified to separate f32 and f64 codes.
Comments and corrections welcome, especially on the documentation.
<!--
```
fn foo() {
// file_test.v
...
}
```
Thanks a …

FFT: add based on PocketFFT

---

.github/workflows/deploy-docs.yml
.github/workflows/markdownlint.yml
.github/workflows/shellcheck.yml
.github/workflows/todo.yml
.github/workflows/v-ci.yml
deriv/README.md
diff/README.md
mpi/_cflags.c.v
vlas/README.md
vlas/cflags_d_cblas.v
vlas/cflags_notd_cblas.v
vlas/lapack.v

<!--
```
fn foo() {
// file_test.v
...
}
```
->

MacOS CI - Not working yet but merging :/

---

fun/datainterp.v
vlas/internal/vblas/dgemm.v
vlas/internal/vblas/level2f64.v
vlas/internal/vblas/level3f64.v

This PR silence the notice for array slice.

vblas: silence the notice for array slice
