bin/fmt
bin/test

This PR fixes an issue found by shellcheck: 
```
Line 14:
find . -name '*_test' | xargs rm -f
^-- SC2038: Use -print0/-0 or -exec + to allow for non-alphanumeric filenames.
```

bin: fix bin/test and bin/fmt by using `find .. -exec .. {} +`

---

combinatorics/combinatorics.v
combinatorics/combinatorics_test.v

`fn combinations(data []int, r int) [][]int`
The first of a set of combinatorics functions in a combinatorics module. 
For now using `[]int` instead of `[]T` and returning eagerly as [mentioned](https://github.com/vlang/vsl/issues/31#issuecomment-753367662)
`combinations_with_replacements()` is on its way next.

combinatorics: add combinations

---

la/matrix_ops.v
la/matrix_ops_test.v

The `matrix_inv_small` function takes both the matrix to store the result in _and_ the original matrix as `mut`. This is unnecessary as there are no changes being made to the original. I removed the unnecessary `mut` modifier for the latter. This is already the case for the general inverse function: `matrix_inv`
Additionally, I added a unit test for the same function in the file `matrix_ops_test.v`

remove unnecessary mut and add unit test

---

iter/inf_iters.v
iter/inf_iters_test.v

Made three iterators to mimic python [itertools](https://docs.python.org/3.9/library/itertools.html) three infinite iterators
- `count()`
- `cycle()`
- `repeat()`
As of writing this, generics were still causing crashes; using `f64` instead.

Infinite iterators

---

ml/knn.v
ml/knn_test.v

Users can now specify the weight for each class by using a `map[f64]f64`. This is totally optional, defaulting to weight 1.0 for each class. The way it works is exactly the same as the previous non-weighted KNN, except that it divides distance by weight in order to find the most suitable neighbors. I am unsure if this is the best approach but it makes sense in my head. Let me know if there is something wrong with this concept.
I also added a zerodiv check (used the proper vsl.error this time instead of a V panic 😛), but if I set any weight to zero there is a runtime error going on. I can't see what's wrong with my if statement, if I print the variable `v` (line 61 of ml/knn.v) it shows 0 just fine but gives me an invalid memory access error.
Digging deep into this, I can only assume it is …

Add weight support for KNN (backwards compatible)

---

ml/knn.v
ml/knn_test.v

For some reason, sorting knn.neighbors changes some things that should not be changed. In a test I did I got this:
```
[48, 671] to [215, 619]: 174.9085475327035
[48, 671] to [850, 154]: 954.1975686407925
[48, 671] to [48, 671]: 0
Looking at: [48, 671]
Closest neighbor:
vsl.ml.Neighbor{
point: [850, 154]
class: 1
distance: 0
}
Returning 1
```
All I did was clone knn.neighbors to a mut array and use this array instead. Weird thing, man... weird thing.

Fixed major inplace sorting bug in KNN.predict

---

blas/vlas/level1f64.v
ml/count_vectorizer.v
ml/lancaster_stemmer.v
ml/tf_idf.v
ml/tokenizer.v
vmath/math.v
vmath/vimpl/q_rsqrt.v
vmath/vimpl/q_rsqrt_test.v

I have added a few NLP tools that rely on ngrams. These include:
- An adaptation of LancasterStemmer from NLTK's source code (`lancaster_stemmer.v` contains a comment giving all credits to the NLTK Project and Steven Tomcavage);
- A very basic tokenizer based on whitespaces and punctuation;
- A punctuation remover;
- A count vectorizer to turn an array of ngrams into a numeric representation of their frequencies in a sentence;
- A stopword remover using common english stopwords (as well as an implementation to add your own stopwords).
- A TF-IDF implementation for slightly more complex NLP models
I also removed two unused iterator variables from `blas/vlas/level1f64.v` because V warnings were annoying me.
Last but not least, I have added `fn q_rsqrt(x f64) f64` in `vmath/math.v` (wrapper) …

Add NLP tools and fast inverse square root

---

ml/count_vectorizer.v
ml/nlp_examples/sentiment_analysis.v
ml/tf_idf.v

This PR adds a sentiment analysis example in `ml/nlp_examples` using KNN, Bag of Words and TF-IDF. It also removes a TODO comment in vdocs, as well as fixing a vdoc "Example:" and missing \`. Check diffs for more info.

Add sentiment analysis example and fix vdocs

---

plot/axis.v
plot/examples/scatter.v
plot/plotter.py

This PR allows the user to specify a fixed range for the plot. Sample code:
```v
import vsl.plot
fn main() {
mut my_vals := [5., 6, 7, 8, 9, 10]
mut p := plot.Plot{}
p.add_trace(
trace_type: .scatter,
x: my_vals
)
p.set_layout(
xaxis: plot.Axis{
tickmode: 'linear', // or 'array' if you specify Axis.tickvals and/or ticktext
range: [0., 15], // lower and upper bounds, inclusive
}
)
p.show() ?
}
```
Did not break anything for `plot/examples`.
I've also fixed scatter.v, that broke when plot.Line and plot.Marker were introduced.

Fixes plot/examples/scatter.v and adds fixed range support

---

la/densesol.v
la/densesol_test.v

Apparently den_solve function to solve Ax=b for x was giving incorrect results because of some issues with the call to blas.dgesv.
Here I propose a couple fixes:
- transpose the A matrix because of the different ordering of the Matrix.data field (col major) vs what blas expects (row major)
- set the "leading dimension of b" argument equal to the number of columns of b instead of rows.
I also added a test to verify that the proposed implementation gives sensible results.

la: fix den_solve

---

plot/plot.v
plot/plot_test.v

It is possible to run tests now using `vsl.plot`. It won't execute the `show` function when running tests.
This fixes #76

Updated compilation time for tests using VSL Plot

---

iter/comb.v

This is an attempt to make `vsl` compatible with https://github.com/vlang/v/pull/14078.
These are the current errors: https://github.com/vlang/v/runs/6094279688?check_suite_focus=true.
<!--
```
fn foo() {
// file_test.v
...
}
```
Applying labels to PRs is not …

Make CombinationsIter.pos unsigned like .size

---

noise/perlin.v

it seems i forgot to remove a println() in the code. naturally, that should not be there.

noise: remove debug println

---

prime/prime.v

It should be safe to round the number down because when rounding it up, the last `i` can never be a divisor of `p` as even 2 * `i` is greater than `p`.
The `prime_test` test now passes more than 2 times faster for me.

`prime`: optimize the `is_prime` function and fix a typo

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature-request.yml

Field suggested using v doctor output, but only gave a single line input. This changes the input to a textarea to handle the full output of the tool.

github: change Environment field to textarea to handle `v doctor` output

---

examples/hdf5_relax/main.v
hdf5/README.md
hdf5/_cflags.c.v
hdf5/hdf5_nix.c.v
hdf5/readhdf5_test.v
hdf5/three_d_test.v
hdf5/two_d_test.v
hdf5/typeshdf5_test.v
hdf5/utils.v
hdf5/v.mod

Add support for HDF5 library.
HDF5 is a data model, library, and file format for storing and managing data.
This module provides basic support for numeric arrays, scalars and related numeric and string attributes.
See the README and the example.
Website https://hdfgroup.org/solutions/hdf5
Comments and reviews welcome of course.
<!--
```
fn foo() {
// file_test.v
...
}
```
- …

add HDF5 support

---

fft/fft.c.v
io/h5/README.md
io/h5/TODO.md
io/h5/_cflags.c.v
io/h5/hdf5_nix.c.v

Update the TODO, minor spelling corrections, and re-do the openbsd and freebsd library flags.
The change to the io/h5/README.md file ensures different random numbers not just copies of a single number.
<!--
```
fn foo() {
// file_test.v
...
}
```
Applying labels …

h5: spelling and TODO updates

---

examples/ml_linreg_plot/main.v

This PR fix array.map() using index variable.

examples: fix array.map() using index variable

---

vcl/device.c.v

This PR fix enum fields with duplicate value.
```v
/home/runner/.vmodules/vsl/vcl/device.c.v:8:19: error: enum value `1` already exists
6 |     gpu = (1 << 1)
7 |     accelerator = (1 << 2)
8 |     default_device = (1 << 0)
|                      ~~~~~~~~
9 |     all = 0xFFFFFFFF
10 | }
```

vcl: fix enum fields with duplicate value

---

examples/plot_scatter3d_easing/main.v
examples/plot_scatter_easing/main.v
examples/plot_surface_easing/main.v

Currently, I'm running into an error when trying to run the plot examples related to the changes in this PR. This update of the import allows me to run the plot examples. 
<!--
```
fn foo() {
// file_test.v
...
}
```
Thanks …

Fix easings import in plot examples

---

gm/basicgm.v
ml/data.v
ml/kmeans.v
ml/knn.v
ml/linreg.v
ml/workspace.v
vcl/buffer.c.v
vcl/bytes.c.v
vcl/image.c.v
vcl/kernel.c.v
vcl/vector.c.v

for green CI:
https://github.com/vlang/v/pull/19944

set nil as the initial value of the struct reference type fields
